resolver: lts-9.21

flags: {}

extra-package-dbs: []

packages:
- location: .
- location: ../focus-prelude
  extra-dep: true
# - location:
#     git: git@github.com:SuperpowersCorp/focus-prelude.git
#     commit: 00a1fb42e4c5b559e88f25d94feb108aff6ed734
#   extra-dep: true
- location:
    git: git@github.com:SuperpowersCorp/luthor.git
    commit: 3228000b6419aee72bdf097d8f4864de0fe789c1
  extra-dep: true

extra-deps:
- protolude-0.2.1
- safe-exceptions-0.1.7.0
- validation-0.6.2
