resolver: lts-8.17

flags: {}

extra-package-dbs: []

packages:
- location: "."
- location:
    git: git@github.com:SuperpowersCorp/focus.git
    commit: 2d2807337c35007d2fbf3c1b1d5e8462373ec257
  extra-dep: true
- location:
    git: git@github.com:SuperpowersCorp/luthor.git
    commit: a216c69e3751e66d9d2d746c9f8307e4c7dd97aa
  extra-dep: true

extra-deps:
- protolude-0.2
