resolver: lts-8.17

flags: {}

extra-package-dbs: []

packages:
- location: "."
- location:
    git: git@github.com:SuperpowersCorp/focus.git
    commit: 659ff7c9a071e45e46b30d2de2c170b629a71fb6
  extra-dep: true
- location:
    git: git@github.com:SuperpowersCorp/luthor.git
    commit: a216c69e3751e66d9d2d746c9f8307e4c7dd97aa
  extra-dep: true

extra-deps:
- protolude-0.2
- validation-0.6.2

