#resolver: lts-8.19
resolver: lts-8.17

flags: {}

extra-package-dbs: []

packages:
- location: '.'
# - location:
#     git: https://github.com/haskell/unix.git
#     commit: fcaa530a8fdd3897353bdf246752a91d675aad46
#   extra-dep: true

extra-deps: []
# - aeson-1.2.1.0
# - directory-1.3.1.1
# - time-1.8.0.2
