resolver: lts-9.21

flags: {}

extra-package-dbs: []

packages:
- location: "."
- location:
    git: git@github.com:SuperpowersCorp/focus-prelude.git
    commit: be316f3b79a58f4cda42d880f2528279666b3605
  extra-dep: true
- location:
    git: git@github.com:SuperpowersCorp/luthor.git
    commit: e208b305fde6fe0a1962f21dbe5f0bbce374e673
  extra-dep: true

extra-deps:
- protolude-0.2
- safe-exceptions-0.1.7.0
- validation-0.6.2
