resolver: lts-8.17

flags: {}

extra-package-dbs: []

packages:
- location: "."
- location:
    git: git@github.com:SuperpowersCorp/infinity.git
    commit: 0519411e11a98c6944a355c7bf979dc15f4838e9
  extra-dep: true
- location:
    git: git@github.com:SuperpowersCorp/luthor.git
    commit: 32a96510f760e70c1912d8d8e4a905e3e5160358
  extra-dep: true

extra-deps: []
