resolver: lts-8.17

flags: {}

extra-package-dbs: []

packages:
- location: "."
- location:
    git: git@github.com:SuperpowersCorp/infinity.git
    commit: 0519411e11a98c6944a355c7bf979dc15f4838e9
  extra-dep: true
- location: ./spc-luthor
  extra-dep: true

extra-deps: []
