resolver: lts-8.17

flags: {}

extra-package-dbs: []

packages:
- location: "."
- location:
    git: git@github.com:SuperpowersCorp/focus-prelude.git
    commit: ad60d24784b1905bbbc2cdbfbec0444b7dc7df86
  extra-dep: true
- location:
    git: git@github.com:SuperpowersCorp/luthor.git
    commit: 6987b27f3278d526b44e3817a7a863c94913d881
  extra-dep: true

extra-deps:
- protolude-0.2
- validation-0.6.2

